### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by jdittrich** [nwutils/nw-sample-apps#30]
**User Story:**  As a programmer I may want to use some of the sample app code in my own (possibly open source) code.

**Problem:** The repo does not a license

**Suggestion:** Add a license which makes clear, if the code is proprietary or could be used in own projects. (The [chrome apps example-repo](https://github.com/GoogleChrome/chrome-app-samples/blob/master/LICENSE) from with which this repo is seemingly related, uses the [Apache 2.0 license](https://github.com/GoogleChrome/chrome-app-samples/blob/master/LICENSE))

**Comment by sapioit** [comment]
If there is no licence, and the code is open-source, than the code is "free_for_all"...  But that might depend on what country you are from...

**Comment by jdittrich** [comment]
As far as I am concerned, in the  US and Europe it is not the case that code without a license is public domain. Like for anything else (Images, Music...) the normal copyright applies in these jurisdiction, if not specified otherwise.

**Comment by sapioit** [comment]
I tried adding the MIT Licence, but the question is if the pull request is accepted... https://github.com/zcbenz/nw-sample-apps/pull/36

**Comment by jdittrich** [comment]
thanks!
